name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  dist:
    permissions:
      contents: read
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo-dist
        uses: axodotdev/cargo-dist-action@v1
        with:
          dist-version: latest
          args: build --artifacts=global

      - name: Attest release build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/*
